const reslist = [
  {
    restaurantId: 111,
    name: 'Pizza Palace',
    cuisine: 'Italian',
    rating: 4.5,
    address: {
      street: '789 Oak St',
      city: 'Springfield',
      state: 'IL',
      zip: '62701',
    },
    deliveryTime: 30,
    cloudinaryImageId: 'ANd9GcQ50q8cpnLo_klq2bT_6Fgj6dFSspX9FYPUpg&s',
    costForTwoString: 25000,
  },
  {
    restaurantId: 112,
    name: 'Sushi Spot',
    cuisine: 'Japanese',
    rating: 4.8,
    address: {
      street: '321 Maple St',
      city: 'Springfield',
      state: 'IL',
      zip: '62701',
    },
    deliveryTime: 20,
    cloudinaryImageId: 'ANd9GcSj9FXoPwvmy_YQAaC2EOfp1ts6lZe_avArfQ&s',
    costForTwoString: 27000,
  },
  {
    restaurantId: 113,
    name: 'Burger Barn',
    cuisine: 'American',
    rating: 4.2,
    address: {
      street: '456 Pine St',
      city: 'Springfield',
      state: 'IL',
      zip: '62701',
    },
    deliveryTime: 25,
    cloudinaryImageId: 'ANd9GcS3Jy98Z74aL0G0joC_rExzsX_QBv-rDEJTfg&s',
    costForTwoString: 22000,
  },
  {
    restaurantId: 114,
    name: 'Taco Town',
    cuisine: 'Mexican',
    rating: 4.6,
    address: {
      street: '789 Birch St',
      city: 'Springfield',
      state: 'IL',
      zip: '62701',
    },
    deliveryTime: 35,
    cloudinaryImageId: 'ANd9GcTYWC-p-SeWYxObNxMzH9fbnR-AOeOWsjK9SQ&s',
    costForTwoString: 24000,
  },
  {
    restaurantId: 115,
    name: 'Pasta Place',
    cuisine: 'Italian',
    rating: 3.7,
    address: {
      street: '123 Cedar St',
      city: 'Springfield',
      state: 'IL',
      zip: '62701',
    },
    deliveryTime: 40,
    cloudinaryImageId: 'ANd9GcRguVNG0f9stRjw3fqLEZeOlmXs6bxEyaEEzw&s',
    costForTwoString: 28000,
  },
  {
    restaurantId: 116,
    name: 'Indian Delight',
    cuisine: 'Indian',
    rating: 4.9,
    address: {
      street: '456 Maple St',
      city: 'Springfield',
      state: 'IL',
      zip: '62701',
    },
    deliveryTime: 50,
    cloudinaryImageId: 'ANd9GcSgLMvo9Hhk3jiSrXm-ONKvOf75GIf6dh57bA&s',
    costForTwoString: 30000,
  },
  {
    restaurantId: 117,
    name: 'BBQ Heaven',
    cuisine: 'Barbecue',
    rating: 3.8,
    address: {
      street: '123 Walnut St',
      city: 'Springfield',
      state: 'IL',
      zip: '62701',
    },
    deliveryTime: 45,
    cloudinaryImageId: 'ANd9GcT0J8HtVADfhiSug0XIa4RNv-5h6IywSivj_g&s',
    costForTwoString: 26000,
  },
  {
    restaurantId: 108,
    name: 'Dessert Haven',
    cuisine: 'Desserts',
    rating: 4.9,
    address: {
      street: '456 Cherry St',
      city: 'Springfield',
      state: 'IL',
      zip: '62701',
    },
    deliveryTime: 25,
    cloudinaryImageId: 'ANd9GcS5BTd73SRzXUw_7eSxNDBaJAnOFj-KR35M5A&s',
    costForTwoString: 23000,
  },
  {
    restaurantId: 109,
    name: 'Vegan Paradise',
    cuisine: 'Vegan',
    rating: 3.4,
    address: {
      street: '789 Spruce St',
      city: 'Springfield',
      state: 'IL',
      zip: '62701',
    },
    deliveryTime: 30,
    cloudinaryImageId: 'ANd9GcRwdUnGhCgzCX2CjDiX7aSBBKaJxNkd5EeIHA&s',
    costForTwoString: 24000,
  },
  {
    restaurantId: 110,
    name: 'Seafood Shack',
    cuisine: 'Seafood',
    rating: 3.0,
    address: {
      street: '123 Ocean Dr',
      city: 'Springfield',
      state: 'IL',
      zip: '62701',
    },
    deliveryTime: 40,
    cloudinaryImageId: 'ANd9GcSSij2TtWzIPOA9O6TdfrD-WMDAikA5-RSzCw&s',
    costForTwoString: 29000,
  },
];

export default reslist;
